version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/iac"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
